### ISSUE TITLE
__dirname 解释错误

### ISSUE THREAD

**Issue by lihuabest** [dwqs/blog#47]
__dirname的值 根据我一般体验是获取当前模块的绝对路径吧 ， 至少好像不是什么项目根目录的解释

**Comment by rccoder** [comment]
In Node.js, __dirname is always the directory in which the currently executing script resides (see this). In other words, you typed __dirname into one of your script files and value would be that file's directory.


http://stackoverflow.com/questions/8131344/what-is-the-difference-between-dirname-and-in-node-js
